a = input("Digite um valor: ")
print(f'O tipo primitivo desse valor é: {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É um número? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em maiusculas? {a.isupper()}')
print(f'Está em minusculas? {a.islower()}')
print(f'Está capitalizada? {a.istitle()}')
